import type { ProductFormDTO } from "@/modules/catalog/types/product.dto";
import type { CategoryListItem } from "@de-tin-marin/validations/category";

export type ProductFormValues = {
  sku: string;
  name: string;
  description: string;
  slug: string;
  brand: string;
  productType: "unit" | "package";
  itemsPerPackage: number;
  packageLabel: string;
  packageNetPrice: number;
  stockSealedPackages: number;
  stockLooseBaseUnits: number;
  purchaseMinQuantity: number;
  purchaseMaxQuantity: number;
  categoryId: string;
  imageUrl: string;
  isActive: boolean;
};

export type ProductFormLabels = {
  breadcrumbParent: string;
  breadcrumbCurrent: string;
  title: string;
  status: string;
  statusActive: string;
  statusInactive: string;
  statusToggle: string;
  sku: string;
  skuPlaceholder: string;
  name: string;
  namePlaceholder: string;
  slug: string;
  slugPrefix: string;
  slugPlaceholder: string;
  image: string;
  imagePreview: string;
  imageAlt: string;
  imageUrl: string;
  imageUrlPlaceholder: string;
  brand: string;
  brandPlaceholder: string;
  category: string;
  categoryPlaceholder: string;
  productType: string;
  productTypeUnit: string;
  productTypePackage: string;
  productTypeHint: string;
  packageSection: string;
  itemsPerPackage: string;
  packageLabel: string;
  packageLabelPlaceholder: string;
  packagePrice: string;
  unitPrice: string;
  unitPricePreview: string;
  stock: string;
  stockSealed: string;
  stockLoose: string;
  stockUnitsOnly: string;
  stockDecrease: string;
  stockIncrease: string;
  purchaseLimits: string;
  purchaseMinQuantity: string;
  purchaseMaxQuantity: string;
  purchaseLimitsHint: string;
  description: string;
  descriptionPlaceholder: string;
  tipTitle: string;
  tipBody: string;
  cancel: string;
  save: string;
  saving: string;
  formatUnitPrice: (price: string) => string;
  formatStockTotal: (total: number) => string;
};

export type ProductFormProps = {
  initial?: ProductFormDTO;
  categories: CategoryListItem[];
  labels: ProductFormLabels;
  onSubmit: (values: ProductFormValues) => Promise<void>;
  onCancel: () => void;
  submitting: boolean;
  error: string | null;
};
